#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
FIRMWARE_DIR="${REPO_ROOT}/boatlock"

BOATLOCK_NH02_SSH_TARGET="${BOATLOCK_NH02_SSH_TARGET:-root@192.168.88.61}"
BOATLOCK_NH02_SSH_PORT="${BOATLOCK_NH02_SSH_PORT:-22}"
BOATLOCK_NH02_REMOTE_ROOT="${BOATLOCK_NH02_REMOTE_ROOT:-/opt/boatlock-hw}"
BOATLOCK_NH02_REMOTE_STAGE="${BOATLOCK_NH02_REMOTE_STAGE:-${BOATLOCK_NH02_REMOTE_ROOT}/stage/esp32s3}"
BOATLOCK_NH02_REMOTE_FLASH_BIN="${BOATLOCK_NH02_REMOTE_FLASH_BIN:-${BOATLOCK_NH02_REMOTE_ROOT}/bin/boatlock-flash-esp32s3.sh}"
BOATLOCK_NH02_REMOTE_RESET_BIN="${BOATLOCK_NH02_REMOTE_RESET_BIN:-${BOATLOCK_NH02_REMOTE_ROOT}/bin/boatlock-reset-esp32s3.sh}"
BOATLOCK_NH02_REMOTE_ANDROID_TOOLS_BIN="${BOATLOCK_NH02_REMOTE_ANDROID_TOOLS_BIN:-${BOATLOCK_NH02_REMOTE_ROOT}/bin/boatlock-ensure-android-tools.sh}"
BOATLOCK_NH02_REMOTE_ANDROID_SMOKE_BIN="${BOATLOCK_NH02_REMOTE_ANDROID_SMOKE_BIN:-${BOATLOCK_NH02_REMOTE_ROOT}/bin/boatlock-run-android-smoke.sh}"
BOATLOCK_NH02_REMOTE_ANDROID_PREP_BIN="${BOATLOCK_NH02_REMOTE_ANDROID_PREP_BIN:-${BOATLOCK_NH02_REMOTE_ROOT}/bin/boatlock-prepare-android-debug.sh}"
BOATLOCK_NH02_REMOTE_ANDROID_WIFI_DEBUG_BIN="${BOATLOCK_NH02_REMOTE_ANDROID_WIFI_DEBUG_BIN:-${BOATLOCK_NH02_REMOTE_ROOT}/bin/boatlock-enable-android-wifi-debug.sh}"
BOATLOCK_NH02_REMOTE_RFC2217_SERVICE="${BOATLOCK_NH02_REMOTE_RFC2217_SERVICE:-boatlock-esp32s3-rfc2217.service}"
BOATLOCK_NH02_REMOTE_USB_DEV="${BOATLOCK_NH02_REMOTE_USB_DEV:-/dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_98:88:E0:03:BA:5C-if00}"
BOATLOCK_NH02_REMOTE_ANDROID_STAGE="${BOATLOCK_NH02_REMOTE_ANDROID_STAGE:-${BOATLOCK_NH02_REMOTE_ROOT}/stage/android}"
BOATLOCK_NH02_RFC2217_PORT="${BOATLOCK_NH02_RFC2217_PORT:-4000}"
BOATLOCK_NH02_RFC2217_HOST="${BOATLOCK_NH02_RFC2217_HOST:-192.168.88.61}"
BOATLOCK_NH02_RFC2217_URL="${BOATLOCK_NH02_RFC2217_URL:-rfc2217://${BOATLOCK_NH02_RFC2217_HOST}:${BOATLOCK_NH02_RFC2217_PORT}?ign_set_control}"
BOATLOCK_NH02_ANDROID_PHONE_USB_GREP="${BOATLOCK_NH02_ANDROID_PHONE_USB_GREP:-Android|MTP|Xiaomi|Google|Samsung|OnePlus|HUAWEI|HONOR}"
BOATLOCK_PIO_PYTHON="${BOATLOCK_PIO_PYTHON:-/Users/user/.platformio/penv/bin/python}"
BOATLOCK_PIO_BIN="${BOATLOCK_PIO_BIN:-/Users/user/.platformio/penv/bin/pio}"
BOATLOCK_MINITERM_BIN="${BOATLOCK_MINITERM_BIN:-/Users/user/.platformio/penv/bin/pyserial-miniterm}"

SSH_BASE=(ssh -p "${BOATLOCK_NH02_SSH_PORT}" "${BOATLOCK_NH02_SSH_TARGET}")
RSYNC_BASE=(rsync -a -e "ssh -p ${BOATLOCK_NH02_SSH_PORT}")

remote_shell() {
  "${SSH_BASE[@]}" "$@"
}

boatlock_nh02_android_wifi_serial() {
  local output
  output="$(remote_shell "'${BOATLOCK_NH02_REMOTE_ANDROID_WIFI_DEBUG_BIN}'" 2>&1)"
  printf '%s\n' "${output}" >&2
  printf '%s\n' "${output}" | awk -F= '/^android_wifi_serial=/ { print $2; exit }'
}
